import type { Metadata } from "next";

import "./globals.css";
import { titleFont, geistSans } from "@/config/font";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${titleFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
